site_name: Mongoose Server
site_description: High-performance, event-driven server framework
site_url: https://telaminai.github.io/mongoose/
repo_url: https://github.com/telaminai/mongoose
repo_name: telaminai/mongoose
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: blue
      accent: indigo

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - attr_list
  - tables

plugins:
  - search
  - mermaid2
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/telaminai
  # Define variables here
  source_root: https://github.com/telaminai/mongoose/tree/main/src
  example_root: https://github.com/telaminai/mongoose-examples/tree/main
  mongoose_version: 1.0.5
  release_date: "2024-09-13"

nav:
  - Home:
      - index: index.md
      - Why Mongoose: overview/mongoose-two-page-intro.md
      - Mongoose for managers: overview/everyone-overview.md
      - Mongoose for engineers: overview/engineers-overview.md
      - Event driven programming: reference/event-driven-programming-explained.md
  - Getting started:
      - 5-minute tutorial: getting-started/five-minute-event-handler-tutorial.md
      - Yaml configuration tutorial: getting-started/five-minute-yaml-configuration-tutorial.md
  - Component overview:
      - Composing a server: overview/configuration-and-composition.md
      - Event source feeds: overview/event-sources-overview.md
      - Event handling business logic: overview/event-processing-architecture.md
      - Event sink outputs: overview/event-sinks-overview.md
      - Service functions: overview/services-overview.md
      - Plugin extension mechanism: overview/plugin_extension_architecture.md
  - Examples and how-to:
      - Example repo: example/example-repo-index.md
      - Plugin examples:
          - Event sink plugin: example/plugin/writing-a-message-sink-plugin.md
          - Event source plugin: example/plugin/writing-an-event-source-plugin.md
          - Service plugin: example/plugin/writing-a-service-plugin.md
          - Service plugin as event feed: example/plugin/writing-a-publishing-service-plugin.md
          - Service plugin with custom dispatch: example/plugin/writing-a-typed-invoke-publishing-service-plugin.md
      - How-to:
          - Subscribe to named event feeds: example/how-to/how-to-subscribing-to-named-event-feeds.md
          - Using the scheduler service: example/how-to/how-to-using-the-scheduler-service.md
          - Inject config into a processor: example/how-to/how-to-injecting-config-into-a-processor.md
          - Transform events: example/how-to/how-to-data-mapping.md
          - Schedule re-entrant events: example/how-to/how-to-scheduler-processAsNewEventCycle.md
          - Add an admin command: example/how-to/how-to-write-an-admin-command.md
          - Pipe messages between handlers: example/how-to/how-to-handler-pipe.md
          - Event replay and synthetic time: example/how-to/how-to-replay.md
          - Write a custom EventToInvokeStrategy: example/how-to/how-to-writing-a-custom-event-to-invoke-strategy.md
          - Event source read strategy: guide/read-strategy.md
          - Zero‑GC object pooling: example/how-to/how-to-object-pool.md
          - Core pin agent threads: example/how-to/how-to-core-pin.md
  - Reference guide:
      - Glossary: reference/glossary.md
      - Architecture and design:
          - Doc description: architecture/index.md
          - Overview: architecture/overview.md
          - Components: architecture/components.md
          - Event flow: architecture/event-flow.md
          - Sequence diagrams:
              - Overview: architecture/sequence-diagrams/index.md
              - Sequence event subscription: architecture/sequence-diagrams/event-subscription.md
              - Sequence event processing: architecture/sequence-diagrams/event-processing.md
          - Agent Execution: architecture/agent-execution.md
          - Threading model: architecture/threading-model.md
          - Object pooling: architecture/object_pooling.md
          - Server control: architecture/server-control.md
      - Reference:
          - Troubleshooting and FAQ: reference/troubleshooting.md
          - Comparisons: reference/comparisons.md
          - Modulith suitability: reference/modulith-suitability.md
          - Operations runbook: reference/operations-runbook.md
          - API Reference: https://javadoc.io/doc/com.telamin/mongoose/latest/index.html
      - Server benchmarks and performance: reports/server-benchmarks-and-performance.md
