name: MavenCI

on:
  push:
    paths-ignore:
      - docs/**
      - _sass/**
      - README.md
      - images/**
    branches-ignore:
      - release
  pull_request:
    branches: [ main, develop ]


jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against the latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 17, 21 ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v4
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project with Maven
        run: mvn -B package --file pom.xml
